name: 2dgs-acescg-py310
channels:
  - pytorch
  - nvidia/label/cuda-11.8.0
  - conda-forge
  - defaults
dependencies:
  - gxx=11
  - gcc=11
  - cuda=11.8
  - cudatoolkit=11.8
  - ffmpeg=4.2.2
  - pillow=10.4.0
  - pip=23.3.1
  - python=3.10
  - pytorch=2.0.0
  - torchaudio=2.0.0
  - torchvision=0.15.0
  - typing_extensions=4.9.0
  - pip:
    - colour-science==0.4.6
    - open3d==0.18.0
    - mediapy==1.1.2
    - lpips==0.1.4
    - scikit-image==0.21.0
    - tqdm==4.66.2
    - trimesh==4.3.2
    - submodules/diff-surfel-rasterization
    - submodules/simple-knn
    - plyfile
    - opencv-python
